# Font style metadata
name = "My_Set_font"

# Optional Google font URL
google_fonts = "family=Palette+Mosaic&Quicksand:wght@300;400;500;600;700&Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700"

# Font families
heading_font = "Palette+Mosaic"
body_font = "Palette+Mosaic"
nav_font = "Palette+Mosaic"
mono_font = "Palette+Mosaic"