---
title: R for Data Science
summary: Linear regression - Covid-19
author: 'Giacomo Baldo'
date: '2021-08-17'
slug: ''
categories: ["R"]
tags: ["R", "Data Science", "Linear regression"]
image:
  caption: ''
  focal_point: ''
  preview_only: no
output:
  blogdown::html_page:
    df_print: kable  #kable, tibble, and paged are also options
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>
<script src="{{< blogdown/postref >}}index_files/kePrint/kePrint.js"></script>
<link href="{{< blogdown/postref >}}index_files/lightable/lightable.css" rel="stylesheet" />


<div id="linear-regression-using-ggplot-and-dplyr." class="section level1">
<h1><mark> Linear regression </mark> using <mark>ggplot()</mark> and <mark>dplyr</mark>.</h1>
<p>This page starts by setting up the options for this document and loading the R libraries required later.</p>
<pre class="r"><code>knitr::opts_chunk$set(message = FALSE, warning=FALSE)</code></pre>
<pre class="r"><code>library(tidyverse)         # for graphing and data cleaning
library(kableExtra)        # for better tables
library(scales)            # to decide between scientific and extended number notation in plots
library(ggrepel)           # to have points&#39; labels displayed nicely in a scatter plot.</code></pre>
<p><strong>Motivation.</strong> In this section I take a look at data related to the Covid-19 epidemic. I will try to answer the following questions: “which EU country was hardest hit by Covid-19?” and “is the wealth of countries a good predictor of deaths due to Covid-19?” At very the end, I’ll include data about press freedom (for reasons that will be made clear).</p>
<p><strong>Where does the data come from?</strong> The data that I use is imported from the European Centre for Disease Prevention and Control (ECDC) website (it does not include data about the United Kingdom). First, I will show a table for the cumulative deaths and cases for each EU country for which data is available in the ECDC dataset. Numbers refer to the pandemic from its beginning to mid august 2021. Second, for each country, I import information about its GDP from the Eurostat website.</p>
<p><strong>The code</strong>. I have used R. The code used is displayed in chunks and the output is rendered in the document.</p>
<p><strong>Outline</strong>. In this page, you will find (not in this order):</p>
<ul>
<li><p>data being imported from separate sources and merged</p></li>
<li><p>a scatter plot with a line of best fit</p></li>
<li><p>a summary of statistics about the linear regression</p></li>
<li><p>a q-q plot for the residuals of the linear regression</p></li>
</ul>
<p> </p>
<div id="cumulative-deaths-and-cases-for-each-country." class="section level2">
<h2>Cumulative deaths and cases for each country.</h2>
<p>Step 1) I import the data, previously downloaded from the ECDC website.</p>
<pre class="r"><code>#read the dataset into “R”. The dataset will be called &quot;data&quot;.
data &lt;- read.csv(&quot;covid-data.csv&quot;)</code></pre>
<p>Step 2) I create a table containing the total number of deaths for each country for which data is available from the ECDC.</p>
<pre class="r"><code>#extract cumulative deaths and cases for each EU country for which data is available
q &lt;- data %&gt;% 
  group_by(countries) %&gt;% 
  summarize(deaths = sum(deaths),
            cases = sum(cases)) %&gt;% 
  arrange(desc(deaths))</code></pre>
<p>Step 3) The data is displayed in a (long) table.</p>
<pre class="r"><code>#plot the table
kbl(q) %&gt;%
   kable_styling(bootstrap_options = c(&quot;responsive&quot;))</code></pre>
<table class="table table-responsive" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
countries
</th>
<th style="text-align:right;">
deaths
</th>
<th style="text-align:right;">
cases
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Italy
</td>
<td style="text-align:right;">
128510
</td>
<td style="text-align:right;">
4449606
</td>
</tr>
<tr>
<td style="text-align:left;">
France
</td>
<td style="text-align:right;">
112943
</td>
<td style="text-align:right;">
6504978
</td>
</tr>
<tr>
<td style="text-align:left;">
Germany
</td>
<td style="text-align:right;">
91921
</td>
<td style="text-align:right;">
3835375
</td>
</tr>
<tr>
<td style="text-align:left;">
Spain
</td>
<td style="text-align:right;">
82739
</td>
<td style="text-align:right;">
4733602
</td>
</tr>
<tr>
<td style="text-align:left;">
Poland
</td>
<td style="text-align:right;">
75306
</td>
<td style="text-align:right;">
2885676
</td>
</tr>
<tr>
<td style="text-align:left;">
Romania
</td>
<td style="text-align:right;">
34359
</td>
<td style="text-align:right;">
1088053
</td>
</tr>
<tr>
<td style="text-align:left;">
Czechia
</td>
<td style="text-align:right;">
30378
</td>
<td style="text-align:right;">
1676817
</td>
</tr>
<tr>
<td style="text-align:left;">
Hungary
</td>
<td style="text-align:right;">
30045
</td>
<td style="text-align:right;">
810658
</td>
</tr>
<tr>
<td style="text-align:left;">
Belgium
</td>
<td style="text-align:right;">
25299
</td>
<td style="text-align:right;">
1156525
</td>
</tr>
<tr>
<td style="text-align:left;">
Bulgaria
</td>
<td style="text-align:right;">
18395
</td>
<td style="text-align:right;">
435940
</td>
</tr>
<tr>
<td style="text-align:left;">
Netherlands
</td>
<td style="text-align:right;">
17920
</td>
<td style="text-align:right;">
1906434
</td>
</tr>
<tr>
<td style="text-align:left;">
Portugal
</td>
<td style="text-align:right;">
17584
</td>
<td style="text-align:right;">
1006588
</td>
</tr>
<tr>
<td style="text-align:left;">
Sweden
</td>
<td style="text-align:right;">
14659
</td>
<td style="text-align:right;">
1112958
</td>
</tr>
<tr>
<td style="text-align:left;">
Greece
</td>
<td style="text-align:right;">
13253
</td>
<td style="text-align:right;">
543749
</td>
</tr>
<tr>
<td style="text-align:left;">
Slovakia
</td>
<td style="text-align:right;">
12544
</td>
<td style="text-align:right;">
779951
</td>
</tr>
<tr>
<td style="text-align:left;">
Austria
</td>
<td style="text-align:right;">
10558
</td>
<td style="text-align:right;">
665862
</td>
</tr>
<tr>
<td style="text-align:left;">
Croatia
</td>
<td style="text-align:right;">
8288
</td>
<td style="text-align:right;">
367409
</td>
</tr>
<tr>
<td style="text-align:left;">
Ireland
</td>
<td style="text-align:right;">
5059
</td>
<td style="text-align:right;">
327684
</td>
</tr>
<tr>
<td style="text-align:left;">
Slovenia
</td>
<td style="text-align:right;">
4764
</td>
<td style="text-align:right;">
262190
</td>
</tr>
<tr>
<td style="text-align:left;">
Lithuania
</td>
<td style="text-align:right;">
4461
</td>
<td style="text-align:right;">
291412
</td>
</tr>
<tr>
<td style="text-align:left;">
Latvia
</td>
<td style="text-align:right;">
2565
</td>
<td style="text-align:right;">
140325
</td>
</tr>
<tr>
<td style="text-align:left;">
Denmark
</td>
<td style="text-align:right;">
2562
</td>
<td style="text-align:right;">
332622
</td>
</tr>
<tr>
<td style="text-align:left;">
Estonia
</td>
<td style="text-align:right;">
1281
</td>
<td style="text-align:right;">
137800
</td>
</tr>
<tr>
<td style="text-align:left;">
Finland
</td>
<td style="text-align:right;">
1006
</td>
<td style="text-align:right;">
118647
</td>
</tr>
<tr>
<td style="text-align:left;">
Luxembourg
</td>
<td style="text-align:right;">
828
</td>
<td style="text-align:right;">
74779
</td>
</tr>
<tr>
<td style="text-align:left;">
Norway
</td>
<td style="text-align:right;">
810
</td>
<td style="text-align:right;">
145012
</td>
</tr>
<tr>
<td style="text-align:left;">
Cyprus
</td>
<td style="text-align:right;">
464
</td>
<td style="text-align:right;">
109665
</td>
</tr>
<tr>
<td style="text-align:left;">
Malta
</td>
<td style="text-align:right;">
433
</td>
<td style="text-align:right;">
35434
</td>
</tr>
<tr>
<td style="text-align:left;">
Liechtenstein
</td>
<td style="text-align:right;">
59
</td>
<td style="text-align:right;">
3185
</td>
</tr>
<tr>
<td style="text-align:left;">
Iceland
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
9682
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>q$countries &lt;- factor(q$countries, levels = q$countries[order(q$deaths)])</code></pre>
<p>Step 4) The same data is displayed in a bar plot.</p>
<pre class="r"><code>z &lt;- ggplot(data = q, mapping = aes(x = deaths, y = countries)) +
  geom_bar(stat=&#39;identity&#39;) +
  theme_light() +
  theme(panel.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;), plot.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;)) +
  scale_x_continuous(name = &quot;Cumulative deaths&quot;, labels = comma) 

z</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-6-1.png" width="672" />
 </p>
</div>
<div id="deaths-per-million-people" class="section level2">
<h2>Deaths per million people</h2>
<p>Although Italy was the hardest hit by the virus in absolute values, it was not in terms of deaths per million. The next plot shows this.</p>
<pre class="r"><code>q &lt;-  data %&gt;% 
  group_by(countries,population) %&gt;% 
  summarize(deaths = sum(deaths))

q &lt;- tibble(countries = q$countries, deaths_pm = q$deaths/q$population*1000000) %&gt;%
  arrange(desc(deaths_pm)) 

q$countries &lt;- factor(q$countries, levels = q$countries[order(q$deaths_pm)])

#create a bar plot of the data above
z &lt;- ggplot(data = q, mapping = aes(x = deaths_pm, y = countries)) +
  geom_bar(stat=&#39;identity&#39;) +
  theme_light() +
  theme(panel.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;), plot.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;)) +
  scale_x_continuous(name = &quot;Deaths per million people&quot;, labels = comma)

#show the plot
z</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-1.png" width="672" />
 </p>
</div>
<div id="deaths-per-million-people-as-a-function-of-per-capita-gdp" class="section level2">
<h2>Deaths per million people as a function of per-capita GDP</h2>
<p>Next, a trend emerges in which countries with a lower per-capita GDP tend to accrue more deaths per million people.</p>
<pre class="r"><code>data &lt;- read.csv(&quot;covid-data.csv&quot;)
gdp_data &lt;- read.csv(&quot;gdp-europe.csv&quot;)
merged_data &lt;- merge(data, gdp_data, by = &quot;countries&quot;)

q &lt;- merged_data %&gt;% 
  group_by(countries,gdp_pp,population) %&gt;% 
  summarize(deaths = sum(deaths))

q &lt;- tibble(countries = q$countries, gdp_pp = q$gdp_pp, deaths_pm = q$deaths/q$population*1000000)

t = ggplot(data = q, mapping = aes(x = gdp_pp, y = deaths_pm)) +
  geom_point() + 
  geom_text_repel(aes(label=countries)) +
  theme_light() +
  scale_x_continuous(name = &quot;GDP per capita (€)&quot;) +
  scale_y_continuous(name = &quot;Deaths per million people&quot;, labels = comma) +
  theme(panel.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;), plot.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;))

t </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-8-1.png" width="672" />
 </p>
</div>
<div id="linear-regression" class="section level2">
<h2>Linear regression</h2>
<p>Now it seems the right time to check for a linear relationship between deaths and GDP. A preliminary analysis has shown that removing the countries with a population smaller than one million from the data set improves the p-values of the regression method.</p>
<p>In the next bit of analysis, first I identify and remove these countries from the data set. Then, I perform the linear regression on the new data set.</p>
<pre class="r"><code>data &lt;- read.csv(&quot;covid-data.csv&quot;)
gdp_data &lt;- read.csv(&quot;gdp-europe.csv&quot;)
merged_data &lt;- merge(data, gdp_data, by = &quot;countries&quot;)

#countries with a population size smaller than one million
c_one_m &lt;- unique(merged_data[which(merged_data$population &lt; 1000000), ]$countries)
c_one_m &lt;- paste(c_one_m, collapse = &quot;, &quot;)
print(paste(&quot; The countries with a population size less than one million are&quot;, c_one_m, sep = &quot; &quot;))</code></pre>
<pre><code>## [1] &quot; The countries with a population size less than one million are Cyprus, Iceland, Luxembourg, Malta&quot;</code></pre>
<pre class="r"><code>#new data set with only countries with a population size over one million
merged_data &lt;- merged_data[(merged_data$population &gt; 1000000), ]

#create a table 
q &lt;- merged_data %&gt;% 
  group_by(countries,gdp_pp,population) %&gt;% 
  summarize(deaths = sum(deaths))

#new table with added column &quot;deaths per million people&quot;
q &lt;- tibble(countries = q$countries, gdp_pp = q$gdp_pp, deaths_pm = q$deaths/q$population*1000000)

#create plot
t &lt;- ggplot(data = q, mapping = aes(x = gdp_pp, y = deaths_pm)) +
  geom_point() + 
  geom_text_repel(aes(label=countries)) +
  theme_light() +
  scale_x_continuous(name = &quot;GDP per capita (€)&quot;) +
  scale_y_continuous(name = &quot;Deaths per million people&quot;, labels = comma) +
  theme(panel.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;), plot.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;))


#add to the graph the line of best fit derived from the linear regression
u &lt;- t +
  geom_smooth(method=&#39;lm&#39;, formula= y~x, se = FALSE)

u</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>#perform linear regression without plotting
m &lt;- lm(deaths_pm ~ gdp_pp, # How does deaths_pm depend on (~) gdp_pp
        data = q) # Look in &quot;q&quot; for the variables

#print summary of linear regression
print(summary(m))</code></pre>
<pre><code>## 
## Call:
## lm(formula = deaths_pm ~ gdp_pp, data = q)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1123.16  -366.32   -40.15   435.28  1050.08 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.414e+03  2.212e+02  10.913 1.43e-10 ***
## gdp_pp      -3.073e-02  7.143e-03  -4.303 0.000265 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 580.7 on 23 degrees of freedom
## Multiple R-squared:  0.446,  Adjusted R-squared:  0.4219 
## F-statistic: 18.51 on 1 and 23 DF,  p-value: 0.0002648</code></pre>
<pre class="r"><code>#print the q-q plot
ggplot() +
  stat_qq(aes(sample = m$residuals)) +
  stat_qq_line(aes(sample = m$residuals)) + 
  theme_light() +
  scale_x_continuous(name = &quot;theoretical quantiles&quot;) +
  scale_y_continuous(name = &quot;sample quantiles&quot;) +
  theme(panel.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;),
plot.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;)) +
  ggtitle(&quot;Q-q plot&quot;) </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-2.png" width="672" />
 </p>
</div>
<div id="comments-on-the-line-of-best-fit" class="section level2">
<h2>Comments on the line of best fit</h2>
<div id="the-line-of-best-fit" class="section level4">
<h4>The line of best fit</h4>
<p>The “coefficients” columns in the summary output tell us that the line of best fit has the following equation:</p>
<p><span class="math display">\[  y = 2.414 \cdot 10^{3} - 3.073 \cdot 10^{-2} \cdot x \]</span>
which is equivalent to</p>
<p><span class="math display">\[  y = 2414 - 0.03073 \cdot x. \]</span></p>
</div>
<div id="interpreting-the-line-of-best-fit" class="section level4">
<h4>Interpreting the line of best fit</h4>
<p>The variable <span class="math inline">\(x\)</span> stands for GDP per capita, while <span class="math inline">\(y\)</span> stands for deaths per million people. The <span class="math inline">\(x\)</span> coefficient tells us that for an increase in €10,000 of per-capita GDP, deaths are expected to reduce by 307 (per million people).</p>
</div>
</div>
<div id="supporting-statistical-evidence" class="section level2">
<h2>Supporting statistical evidence</h2>
<div id="the-p-value" class="section level4">
<h4>The p-value</h4>
<p>The evidence for accepting this relationship is given by the very small p-value given for “gdp_pp” resulted in the linear regression summary statistics. The p-value is equal to 0.000265. In more technical terms (read on if interested in technicalities), this means that we can confidently reject the null-hypothesis (assuming the null-hypothesis to be true, there is only a 0.0265% probability of obtaining a test statistic equal or more extreme than the t-value).</p>
</div>
<div id="the-distribution-of-residuals" class="section level4">
<h4>The distribution of residuals</h4>
<p>The p-value of the standard linear regression performed above is meaningful if the residuals follow a normal distribution. In the summary statistics, one can see that residuals are approximately symmetrically distributed with median close to zero (in relative terms). This is already good evidence for a symmetrical distribution. A more rigorous test for normal distribution is given by a q-q plot, which compares what would be the residuals of data that follow a standard normal distribution to the residuals from the tested data. When the resulting q-q plot follows a straight line, as it roughly does in our case above, the distribution of the residuals does indeed closely follow a normal distribution.</p>
</div>
<div id="r-squared" class="section level4">
<h4>R squared</h4>
<p>The value for R squared is 0.446 (0.4219 when adjusted). As rule of thumb, this implies that just over 40% of the variance of the dependent variable (deaths) is explained by the dependent variable (GDP) alone.</p>
</div>
</div>
<div id="comments" class="section level2">
<h2>Comments</h2>
<p>This analysis points to the outcomes of economic inequalities. Perhaps unsurprisingly, it shows that countries with higher per-capita GDP are better equipped to prevent deaths from Covid-19. Nevertheless, as expected, not all variability in deaths is explained in terms of one variable.</p>
<hr />
</div>
</div>
<div id="press-freedom-and-covid-19-deaths" class="section level1">
<h1>Press freedom and Covid-19 deaths</h1>
<p>In this section, I look at the relationship between freedom of press and cumulative deaths due to Covid-19 for each of the countries considered above. I decided to do so because, as we will see, press freedom is an even stronger predictor than GDP for deaths per million people.
 
Data for deaths is imported from the ECDC (European Centre for Diseases prevention and Control). Data for the GDP is imported from Eurostat. Data for press freedom is imported from RSF (Reporters Sans Frontiers): a lower score implies greater freedom of press.</p>
<p>In the code chunks below, you will find:</p>
<ul>
<li><p>data being imported from separate sources and merged</p></li>
<li><p>a scatter plot with a line of best fit</p></li>
<li><p>a summary of statistics about the linear regression</p></li>
<li><p>a q-q plot for the residuals of the linear regression</p></li>
</ul>
<p> </p>
<pre class="r"><code>data &lt;- read.csv(&quot;covid-data.csv&quot;) # from the ECDC
gdp_data &lt;- read.csv(&quot;gdp-europe.csv&quot;) # from EUROSTAT
merged_data &lt;- merge(data, gdp_data, by = &quot;countries&quot;)
press_fr &lt;- read.csv(&quot;index_2021.csv&quot;) # from Reporters Sans Frontiers
merged_data &lt;- merge(merged_data, press_fr, by = &quot;countries&quot;)

#new data set with only countries with a population size over one million
merged_data &lt;- merged_data[(merged_data$population &gt; 1000000), ]

#create a table
q &lt;- merged_data %&gt;%
  group_by(countries, gdp_pp, population, score) %&gt;%
  summarize(deaths = sum(deaths))

#new table with added column &quot;deaths per million&quot; and &quot;press freedom score&quot;
q &lt;- tibble(countries = q$countries, gdp_pp = q$gdp_pp, deaths_pm = q$deaths/q$population*1000000, press = q$score )

# create plot
t &lt;- ggplot(data = q, mapping = aes(x = press, y = deaths_pm)) +
  geom_point() +
  geom_text_repel(aes(label=countries)) +
  theme_light() +
  scale_x_continuous(name = &quot;Press freedom score 2021&quot;) +
  scale_y_continuous(name = &quot;Deaths per million people&quot;, labels = comma) +
  theme(panel.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;), plot.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;))

#add to the graph the line of best fit derived from the linear regression
u &lt;- t +
  geom_smooth(method=&#39;lm&#39;, formula= y~x, se = FALSE)

print(u)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>#calculate and extract regression statistics summary
m &lt;- lm(deaths_pm ~ press, # How does deaths_pm depend on (~) the 2021 press freedom score
         data = q) # Look in &quot;q&quot; for the variables
print(summary(m))</code></pre>
<pre><code>## 
## Call:
## lm(formula = deaths_pm ~ press, data = q)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1026.8  -284.4  -123.8   359.3  1029.9 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   399.34     247.71   1.612    0.121    
## press          65.56      12.24   5.358 1.93e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 520.3 on 23 degrees of freedom
## Multiple R-squared:  0.5552, Adjusted R-squared:  0.5359 
## F-statistic: 28.71 on 1 and 23 DF,  p-value: 1.928e-05</code></pre>
<pre class="r"><code>#plot the q-q plot for the residuals
pl &lt;- ggplot() +
  stat_qq(aes(sample = m$residuals)) +
  stat_qq_line(aes(sample = m$residuals)) + 
  theme_light() +
  scale_x_continuous(name = &quot;theoretical quantiles&quot;) +
  scale_y_continuous(name = &quot;sample quantiles&quot;) +
  theme(panel.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;),
        plot.background = element_rect(fill = &quot;#F8F9FA&quot;, colour = &quot;#F8F9FA&quot;)) +
  ggtitle(&quot;Q-q plot&quot;) 

plot(pl)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
<div id="comments-on-the-line-of-best-fit-1" class="section level2">
<h2>Comments on the line of best fit</h2>
<div id="the-line-of-best-fit-1" class="section level4">
<h4>The line of best fit</h4>
<p>The “coefficients” columns in the summary output tell us that the line of best fit has the following equation:</p>
<p><span class="math display">\[  y = 399.34 + 65.56 x. \]</span></p>
</div>
<div id="interpreting-the-line-of-best-fit-1" class="section level4">
<h4>Interpreting the line of best fit</h4>
<p>The variable <span class="math inline">\(x\)</span> stands for the freedom of press score, while <span class="math inline">\(y\)</span> stands for deaths per million people. The <span class="math inline">\(x\)</span> coefficient tells us that for a 10-point worsening of the score, deaths are expected to increase by a count of 655 (per million people).</p>
</div>
</div>
<div id="supporting-statistical-evidence-1" class="section level2">
<h2>Supporting statistical evidence</h2>
<div id="the-p-value-1" class="section level4">
<h4>The p-value</h4>
<p>The evidence for accepting this relationship is given by the very small p-value given for “press” resulted in the linear regression summary statistics. The p-value is equal to 0.0000193. In more technical terms (read on if interested in technicalities), this means that we can confidently reject the null-hypothesis (assuming the null-hypothesis to be true, there is only a 0.00193% probability of obtaining a test statistic equal or more extreme than the t-value).</p>
</div>
<div id="the-distribution-of-residuals-1" class="section level4">
<h4>The distribution of residuals</h4>
<p>When the resulting q-q plot follows a straight line, as it roughly does in our case above, the distribution of the residuals closely follows a normal distribution.</p>
</div>
<div id="r-squared-1" class="section level4">
<h4>R squared</h4>
<p>The value for R squared is 0.5552 (0.5359 when adjusted). As rule of thumb, this implies that just over 50% of the variance of the dependent variable (deaths) is explained by the dependent variable (press freedom score) alone.</p>
</div>
</div>
<div id="comments-1" class="section level2">
<h2>Comments</h2>
<p>All statistical predictors tell us that press freedom is a slightly more robust predictor of deaths due to Covid than per-capita GDP. Technically, this is due to a lower p-value, lower standard residual error, higher R-squared coefficient and higher value for the F-statistic.</p>
<div id="ill-be-refining-and-adding-to-this-analysis-in-the-near-future." class="section level4">
<h4>I’ll be refining and adding to this analysis in the near future.</h4>
</div>
</div>
</div>
